### ISSUE TITLE
Review the screenshot process for old sites

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#18]
Whenever we get a new client, we screenshot their current/old site and save it so we at least have a local copy in case we need to refer back to it after they've cancelled their previous hosting contract. 

Please visit pumpkinkingwholesale.com and also look at our google drive for them and view what Raquel did in terms of saving that site. 

This is a process that has to be accurate and comprehensive. Think of it as creating a backup for a hard drive. You would leave a poor review if the backup software you used backed up all your music except the stuff from Eminem. 

Again, review the site, review how Raquel saved the site, and then close this issue with a brief summary of what you think the process is and how you'll use it in the future. 

You better use proper punctuation and be clear in your summary, otherwise I'll make you write a minimum 1,500 word memo about the history of ECMAscript. 

due:
12-28-15   5p

**Comment by rampage1213** [comment]
I will need to push the deadline to 12-28-15 12am

**Comment by rodneystrong** [comment]
Got notified by todoist about this. Any revelations ?

**Comment by rampage1213** [comment]
I see that Raquel has taken screenshots every page on the site, has saved the logos and other assets, and has saved the old code to the google drive. She has also nicely organized it. I googled to see what tools she might have used and I see there are some google extensions that allow to do this. Having a copy of an old site is good because if the client ever wanted their old wedsite back everything is backed up. Also, this gives us all of the content from the current site so we can use it for new site.

**Comment by rodneystrong** [comment]
Not bad at all. Correct insights and glad you googled some possible tools to make your life easier for this process.
